name: Test Version Update Action

on:
  push: {}

jobs:
  prerequisites:
    runs-on: ubuntu-latest
    steps:
      - name: Commit Info
        id: git_info
        run: |
          last_commit_message=$(git log -1 --no-merges --pretty=format:%B)
          echo "last_commit_message=${last_commit_message}"
          echo "last_commit_message<<EOF" >> $GITHUB_OUTPUT
          echo "${last_commit_message}" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

          last_pr_message=$(git log -1 --pretty=format:%B)
          echo "last_pr_message=${last_pr_message}"
          echo "last_pr_message<<EOF" >> $GITHUB_OUTPUT
          echo "${last_pr_message}" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT
  test-single-project:
    name: Test Single Repo
    uses: dragoscirjan/version-update-action/.github/workflows/test-single.yml@main
    secrets: inherit
    with:
      commit_type: feat
      version_message: new single repo version
