name: Test Version Update Action

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:

jobs:
  test-version-update-action:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 # Fetch full history so git log works

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Set up Git
        id: git_info
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git config --global --add safe.directory "$GITHUB_WORKSPACE"

      - name: Create Test Commit
        run: |
          set -e

          date > ./test/node/.update
          git add ./test
          git commit -m "feat: Added a feature"

          last_tag=$(git for-each-ref --sort=-taggerdate --format '%(refname:short)' refs/tags | head -n 1)
          if [[ -z "$last_tag" ]]; then
          #last_tag=$(echo "HEAD~$(git rev-list --count HEAD)")
            last_tag=$(git rev-list --max-parents=0 HEAD)
          fi
          git diff --name-only "$last_tag" HEAD

      - name: Run Version Update Action (single project)
        id: version_update_action_sp
        uses: dragoscirjan/version-update-action@main
        with:
          workspaces: "test/node"
          dry_run: true

      - name: Create Test Commit
        run: |
          date > ./test/node/.update
          git add ./test

          git commit -m "fix: Added a fix"

          last_tag=$(git for-each-ref --sort=-taggerdate --format '%(refname:short)' refs/tags | head -n 1)
          if [[ -z "$last_tag" ]]; then
          #last_tag=$(echo "HEAD~$(git rev-list --count HEAD)")
            last_tag=$(git rev-list --max-parents=0 HEAD)
          fi
          git diff --name-only "$last_tag" HEAD

      - name: Run Version Update Action (multi project)
        id: version_update_action_mp
        uses: dragoscirjan/version-update-action@main
        with:
          workspaces: "test,test/node,test/node-2"
          version_files: VERSION,package.json,pacjage.json
          dry_run: true

      # - name: Create Test Commit
      #   run: |
      #     date > ./test/node/.update
      #     date > ./test/node-2/.update
      #     git add ./test
      #     git commit -m "feat!: Added a breaking change"
      #
      # - name: Run Version Update Action (multi project)
      #   id: version_update_action_mp2
      #   uses: dragoscirjan/version-update-action@main
      #   with:
      #     workspaces: "test,test/node,test/node-2"
      #     version_files: VERSION,package.json,pacjage.json
      #     dry_run: true
