name: Test Version Update Action

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:

jobs:
  test-version-update-action:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - title: single project
            workspaces: test/node
            version_files: package.json
            commit_tag: feat
          - title: multi project
            workspaces: test,test/node,test/node-2
            version_files: VERSION,package.json,package.json
            commit_tag: fix
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 # Fetch full history so git log works

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Set up Git
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git config --global --add safe.directory "$GITHUB_WORKSPACE"

      - name: Commit Info
        id: git_info
        shell: bash
        run: |
          last_commit_message=$(git log -1 --no-merges --pretty=format:%B)
          echo "last_commit_message=${last_commit_message}"
          echo "last_commit_message='${last_commit_message}'" >> $GITHUB_OUTPUT

          last_pr_message=$(git log -1 --pretty=format:%B)
          echo "last_pr_message=${last_pr_message}"
          echo "last_pr_message='${last_pr_message}'" >> $GITHUB_OUTPUT

      - name: Create Test Commit
        if: ${{ ! contains(steps.git_info.outputs.last_commit_message, 'version pull request ') }}
        run: |
          date +%s > ./test/node/.update
          git add ./test
          git commit -m "${{ matrix.commit_tag }}: Added a feature"

      - name: Run Version Update Action (${{ matrix.title }})
        id: version_update_action_sp
        uses: dragoscirjan/version-update-action@main
        with:
          workspaces: "${{ matrix.workspaces }}"
          version_files: "${{ matrix.version_files }}"
          github_token: "${{ secrets.GH_TOKEN }}"
          # github_token: "${{ secrets.GITHUB_TOKEN }}"
          dry_run: true
