name: Test Version Update Action

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:

jobs:
  test-version-update-action:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - title: single project
            workspaces: test/node
            version_files: package.json
            commit_tag: feat
          - title: multi project
            workspaces: test,test/node,test/node-2
            version_files: VERSION,package.json,package.json
            commit_tag: fix
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 # Fetch full history so git log works

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Set up Git
        id: git_info
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git config --global --add safe.directory "$GITHUB_WORKSPACE"

      - name: Create Test Commit
        run: |
          date +%s > ./test/node/.update
          git add ./test
          git commit -m "${{ matrix.commit_tag }}: Added a feature"

      - name: Run Version Update Action (${{ matrix.title }})
        id: version_update_action_sp
        uses: dragoscirjan/version-update-action@main
        with:
          workspaces: "${{ matrix.workspaces }}"
          version_files: "${{ matrix.version_files }}"
          dry_run: true
