name: Test Version Update Action

on:
  push: {}

jobs:
  test-single-project:
    name: Test Single Repo
    uses: dragoscirjan/version-update-action/.github/workflows/test-single.yml@main
    secrets: inherit
    with:
      commit_type: feat
      version_message: new single repo version
